Typography
boostgrade/wtgt_delta pull request #22
Opened 2022-04-26 20:43 UTC by Pasheza

# Ссылка на задачу
Задача [#2](https://github.com/boostgrade/wtgt_delta/issues/2)

# Что было сделано

- Добавлены файлы необходимых шрифтов

- В файл ``` AppTypograhy``` добавлены небходимые текстайлы согласно дизайну.

# Как проверить работу?

- Ознакомиться с изменёнными файлами

(Скриншот со шрифтами добавлю позже)

# Чек-лист

- [ ] Функциональность протестирована и работает корректно
- [ ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2022-04-26 20:45 UTC, Sanlovty approved these changes
Всё красиво вроде

2022-04-26 20:48 UTC, Sanlovty reviewed
Уточняющий момент

2022-04-26 20:48 UTC, Sanlovty commented on lib/src/core/ui/res/typography/typography.dart
>  abstract class AppTypography {
Единственное, @Pasheza, вам нужно сконнектится с @TimurKarev и решить какое в итоге название брать. App или Project. Просто, у Тимура вроде ProjectColors, логично было бы делать и ProjectTypography. Либо, если вы решите делать App, то делать с ним

2022-04-27 03:23 UTC, Sanlovty reviewed
Всё супер

2022-04-27 03:23 UTC, Sanlovty commented on lib/src/core/ui/res/typography/typography.dart
>  }
Пропущен отступ

2022-04-27 03:25 UTC, Sanlovty approved these changes

2022-04-27 03:27 UTC, Sanlovty commented on lib/src/core/ui/res/typography/typography.dart
>  abstract class AppTypography {
Возможно я не прав и ProjectColors названо именно так т.к. скоуп этой палитры - весь проект, и AppColors было бы уместно только возле скоупа App'a. (т.е. возможно добавление для фичи auth AuthColors). Возможно я ошибаюсь, требуется совет @artem-zaitsev

2022-04-27 07:42 UTC, artem-zaitsev requested changes

2022-04-27 07:42 UTC, artem-zaitsev commented on lib/src/core/ui/res/typography/typography.dart
>  abstract class AppTypography {
Нет, Project - просто на тот момент так было придумано)

Тут нет подоплеки. 
Но стоит обсудить всеми в чате и выбрать единый нейминг-префикс

2022-04-27 07:42 UTC, artem-zaitsev commented on lib/src/core/ui/res/typography/typography.dart
>  abstract class AppTypography {
@Sanlovty @TimurKarev @NetLost обратите внимание

2022-04-27 07:42 UTC, artem-zaitsev commented on lib/src/core/ui/res/typography/typography.dart
> +  static const body1 =  TextStyle(
Тут удобно сделать структуру с наследованием стилей.

Вот пример: https://github.com/artem-zaitsev/pick_office/blob/main/lib/src/core/ui/res/app_text_styles.dart

2022-04-27 07:56 UTC, Pasheza commented on lib/src/core/ui/res/typography/typography.dart
> +  static const body1 =  TextStyle(
Ок, исправлю

2022-04-28 05:36 UTC, TimurKarev approved these changes

2022-04-28 08:52 UTC, artem-zaitsev approved these changes
можно сливать

2022-04-28 09:13 UTC, NetLost approved these changes

2022-04-28 09:48 UTC, merged