add base button
boostgrade/wtgt_delta pull request #7
Opened 2022-04-24 18:44 UTC by NetLost

# Ссылка на задачу
Задача #3

# Что было сделано

Реализован базовый компонент кнопки:
1) верстка базового компонента
2) добавлены состояния кнопки: нормальное состояние кнопки, неактивна, обработка функции (показывается лоадер)

# Как проверить работу?

1) Посмотреть внесенные изменения

# Чек-лист

- [ ] Функциональность протестирована и работает корректно
- [ ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

2022-04-24 19:27 UTC, Sanlovty commented
Скоро посмотрю код, добавь пока сторипоинты и залинкуй проблему. @NetLost

2022-04-24 20:31 UTC, Sanlovty requested changes
Немного комментариев с вопросами, нужны изменения в тестах

2022-04-24 20:31 UTC, Sanlovty commented on lib/src/ui/uikit/wtgt_button.dart
> +}
@NetLost, Отступ пропущен

2022-04-24 20:31 UTC, Sanlovty commented on lib/src/ui/uikit/wtgt_button.dart
> +              style: TextStyle(
@NetLost, Стиль в будущем будет вынесет во что-то на подобие ```AppTypography```, поэтому можно добавить TODO с выносом в будущем туда

2022-04-24 20:31 UTC, Sanlovty commented on lib/src/ui/uikit/wtgt_button.dart
> +        fixedSize: MaterialStateProperty.all(const Size.fromHeight(60)),
@NetLost, Почему 60, в фигме вроде 52

2022-04-24 20:31 UTC, Sanlovty commented on lib/src/ui/uikit/wtgt_button.dart
> +          const EdgeInsets.all(8.0),
@NetLost, в фигме вроде 14\16

2022-04-24 20:31 UTC, Sanlovty commented on lib/src/ui/uikit/wtgt_button.dart
> +enum Status {
@NetLost, А что если кнопка не disabled и не loading? Я вижу, что ты посылаешь туда null, но, имхо, не интуитивно понятно. Мне кажется лучше хранить два параметра внутри всего виджета: 1) bool isLoading; 2) bool isDisabled;

2022-04-24 20:31 UTC, Sanlovty commented on test/uikit/wtgt_button_test.dart
>          },
@NetLost, если есть тест на enabled, где test на disabled?

2022-04-26 15:37 UTC, Sanlovty commented on test/uikit/wtgt_button_test.dart
> +        'Если статус кнопки Status.disable - должны увидеть текст',
Мне кажется, нужно немного поправить коммент, ибо не просто текст, а ещё и уменьшенное опасити и т.п.

2022-04-26 15:38 UTC, Sanlovty approved these changes
Критическое исправил, но к комментариям выше, мне кажется, стоило бы прислушаться. Увидим потом. Если Артёму нормально - то у меня претензий нет

2022-04-26 17:48 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +        fixedSize: MaterialStateProperty.all(const Size.fromHeight(60)),
Да, согласен

2022-04-27 06:21 UTC, NetLost commented on lib/src/core/ui/res/colors/colors.dart
> +  static const Color buttonColor = _yellow;
Ну по сути одна + FloatingActionButton. Она просто черная. В целом не знаю. Можно обозвать и baseButtonColor

2022-04-27 06:23 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +  final void Function()? onPressed;
Ну здесь нам теперь надо решить всем вместе, как мы будем писать по всему проекту. Имеет смысл посоветоваться с Лёшей. Но я бы тогда называл, как рекомендуется в оф. документации

2022-04-27 06:24 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +/// Входные параметры: onPressed - callback функции, label - заголовок кнопки,
Да, здесь соглашусь, что опыта у меня нет описания документации. Надо тоже прийти к одному стилю. Надо бы посмотреть опять же в оф. документации, возможно там есть рекомендации

2022-04-27 06:25 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +/// status - состояние кнопки(null - обычное состояние кнопки, disable - кнопка
Да, описание надо бы полностью переписать

2022-04-27 06:27 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +}
А можешь поподробнее?) Просто я что-то о таком правиле впервые слышу) Здесь больше, наверное, зависит от стилистики в какой пишет вся команда. Но в целом мне не сложно и поставить :)

2022-04-27 06:28 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +              style: TextStyle(
Да, делал TODO, но потом стер. Ждем, когда будет у нас ProjectTypography и ProjectTheme

2022-04-27 06:28 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +          const EdgeInsets.all(8.0),
Да, надо поправить

2022-04-27 06:28 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +enum Status {
Теперь появится третье состояние active, которое будет по умолчанию

2022-04-27 06:29 UTC, Sanlovty commented on lib/src/ui/uikit/wtgt_button.dart
> +}
https://semakin.dev/2020/05/no_newline_at_end_of_file/

2022-04-27 07:34 UTC, artem-zaitsev reviewed
Когда внесешь исправления, будет апрув

2022-04-27 07:34 UTC, artem-zaitsev commented on lib/src/core/ui/res/colors/colors.dart
> +  static const Color buttonColor = _yellow;
Стоит алиасы дать такими же , как названия в фигме

2022-04-27 07:34 UTC, artem-zaitsev commented on lib/src/ui/uikit/wtgt_button.dart
> +  final void Function()? onPressed;
Если Леша говорил использовать VoidCallback - берите его. Потом вместе обсудите

2022-04-27 07:34 UTC, artem-zaitsev commented on test/uikit/wtgt_button_test.dart
> +        'Если статус кнопки Status.disable - должны увидеть текст',
Пока оставьте так.

2022-04-28 05:40 UTC, TimurKarev approved these changes

2022-04-28 08:50 UTC, artem-zaitsev approved these changes

2022-05-03 09:55 UTC, HazarD2311 requested changes

2022-05-03 09:55 UTC, HazarD2311 commented on lib/src/ui/uikit/wtgt_button.dart
> +        padding: status == Status.loading
а зачем тут такая разница в отступах?

2022-05-03 09:55 UTC, HazarD2311 commented on lib/src/ui/uikit/wtgt_button.dart
> +        fixedSize: MaterialStateProperty.all(const Size.fromHeight(52)),
перенеси 52 сразу в параметр, будет полезно рано или поздно

2022-05-03 09:55 UTC, HazarD2311 commented on lib/src/ui/uikit/wtgt_button.dart
> +  final Status? status;
почему `Status` nullable? Как может быть кнопка без состояния?

2022-05-03 09:55 UTC, HazarD2311 commented on lib/src/ui/uikit/wtgt_button.dart
> +enum Status {
1. плохое название для статуса.
очень абстрактное и не понятно, что связано с `WtgtButton` кнопкой
2. и я бы всё-таки назвал `..Type`, а не `..Status`, но это на твой выбор

2022-05-03 09:55 UTC, HazarD2311 commented on lib/src/ui/uikit/wtgt_button.dart
>    const WtgtButton({
я бы тут добавил конструкторы отдельные, для большего понимания работы виджета отдельные конструкторы под каждое состояние

2022-05-03 09:55 UTC, HazarD2311 commented on lib/src/ui/uikit/wtgt_button.dart
> +  disable,
кажется это состояние необязательно тут
можно просто переводить кнопку в состояние `disable` - если `onPressed == null`

2022-05-03 09:55 UTC, HazarD2311 commented on lib/src/ui/uikit/wtgt_button.dart
> +  final Status? status;
а что, если я захочу, задизейбленную кнопку с состоянием загрузки? кажется это взаимозаменяемые состояния

2022-05-03 10:39 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +        padding: status == Status.loading
Делал по верстке в фигме

2022-05-03 10:39 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +        fixedSize: MaterialStateProperty.all(const Size.fromHeight(52)),
Сделаю

2022-05-03 10:40 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +  final Status? status;
Забыл исправить, когда добавил новый статус.

2022-05-03 10:40 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +enum Status {
Хорошо. Переименую

2022-05-03 10:41 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
>    const WtgtButton({
Да, можно и так. Но не слишком будет много тогда boilerplate'а?

2022-05-03 10:46 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +  disable,
На предыдущем созвоне Артем аргументировал, что нужно сохранить три состояния тем, чтобы потом было легче делать проверки через статус. Но мне несложно переделать :)

2022-05-03 10:47 UTC, NetLost commented on lib/src/ui/uikit/wtgt_button.dart
> +  final Status? status;
Да, я об этом думал и даже в какой-то реализации делал, но в тз или в фигме такого состояния не существует и я решил пойти по паттерну YAGNI. Так что, если такое состояние необходимо, то сделаю

2022-05-04 14:57 UTC, HazarD2311 commented on lib/src/ui/uikit/wtgt_button.dart
> +        padding: status == Status.loading
кажется всё-таки лишнее, т.к. весь контент можно просто центрировать и эти отступы будут и без паддинга
ну можно так оставить

2022-05-08 06:41 UTC, HazarD2311 approved these changes

2022-05-08 06:42 UTC, merged